[tool.black]
line-length = 119

[tool.isort]
profile = 'black'

[tool.ruff]
line-length = 119
target-version = "py310"
select = ["ALL"]
ignore = [
  "ANN", "COM", "CPY", "D", "EM",
  "B018",  # useless expression (e.g. variable to render)
  "F401",  # imported but unused
  "F821",  # undefined name (e.g. %sql magic assignment)
  "ERA001",  # commented-out code
]

[tool.ruff.flake8-builtins]
builtins-ignorelist = ["copyright"]

[tool.ruff.per-file-ignores]
"template_*" = ["E402"]  # import not at top
