name: Merge notebooks and upload to Google Drive
on:
  push:
    branches:
      - main
env:
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GSA_CREDENTIALS }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: pip install -r requirements.txt
      - name: Merge publisher analysis template
        run: nbmerge setup_environment.ipynb choose_data.ipynb check_for_errors.ipynb check_scope.ipynb > publisher_analysis_template.ipynb
      - name: Merge structure and format feedback template
        run: nbmerge setup_environment.ipynb choose_data.ipynb check_for_errors.ipynb check_scope.ipynb check_structure_and_format.ipynb > structure_and_format_feedback_template.ipynb
      - name: Merge data quality feedback template
        run: nbmerge setup_environment.ipynb choose_data.ipynb check_for_errors.ipynb check_scope.ipynb check_structure_and_format.ipynb check_data_quality.ipynb > data_quality_feedback_template.ipynb
      - run: ./manage.py upload
